-- Initial schema for books table

CREATE TABLE books (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(20),
    year_published INT,
    date_read DATE,
    rating INT,
    total_pages INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    condition VARCHAR(20) NOT NULL DEFAULT 'GOOD',
    location VARCHAR(255),
    qr_code VARCHAR(255),
    date_acquired DATE,
    started_reading TIMESTAMP,
    current_page INTEGER DEFAULT 0,
    last_read_at TIMESTAMP
);

CREATE TABLE book_notes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER,
    content TEXT NOT NULL,
    page INTEGER,
    chapter VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE book_lending (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER,
    borrower_name VARCHAR(255) NOT NULL,
    borrower_contact VARCHAR(255) NOT NULL,
    lending_date TIMESTAMP NOT NULL,
    expected_return_date TIMESTAMP NOT NULL,
    actual_return_date TIMESTAMP,
    notes TEXT,
    FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE reading_progress (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER,
    current_page INTEGER NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    minutes_read INTEGER,
    notes TEXT,
    FOREIGN KEY (book_id) REFERENCES books(id)
);

-- Add indexes
CREATE INDEX idx_book_status ON books(status);
CREATE INDEX idx_book_qr_code ON books(qr_code);
CREATE INDEX idx_book_lending_book_id ON book_lending(book_id);
CREATE INDEX idx_reading_progress_book_id ON reading_progress(book_id);
CREATE INDEX idx_book_notes_book_id ON book_notes(book_id);