-- V3__add_users_with_sso.sql
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL,
    last_login_at TIMESTAMP,
    auth_provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    provider_id VARCHAR(255),
    display_name VARCHAR(255),
    image_url VARCHAR(1024),
    CONSTRAINT uq_provider_id UNIQUE (auth_provider, provider_id)
);

-- Dodajemo user_id kolonu u books tabelu
ALTER TABLE books ADD COLUMN user_id INT NOT NULL;
ALTER TABLE books ADD CONSTRAINT fk_books_user FOREIGN KEY (user_id) REFERENCES users(id);

-- Kreiramo indekse
CREATE INDEX idx_books_user_id ON books(user_id);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_provider ON users(auth_provider, provider_id);